const mongoose = require('mongoose');

/**
 * One associate's figures within one payout batch.
 *
 * A separate collection rather than an array on PayoutBatch: ten thousand
 * members would push a single document past Mongo's 16MB limit, and these rows
 * need their own pagination, search and CSV streaming.
 *
 * Every identity field is a SNAPSHOT, not a lookup. A payout statement is a
 * historical document — it must still read correctly after the member is
 * renamed, re-tiered or removed.
 */
const payoutLineSchema = new mongoose.Schema(
  {
    batch: { type: mongoose.Schema.Types.ObjectId, ref: 'PayoutBatch', required: true, index: true },
    batchNo: { type: String, required: true },

    member: { type: mongoose.Schema.Types.ObjectId, ref: 'Associate', required: true },
    memberCode: { type: String, required: true },
    fullName: { type: String, required: true },
    // Snapshotted for the TDS return. Associate has no `pan` field yet — see
    // PAYOUT-ENGINE-PLAN.md §7.1 — so this is blank until that is added.
    pan: { type: String, default: '', uppercase: true, trim: true },
    tier: { type: String, required: true },

    // Earnings for this period, from the ledger. `total` is net of reversals
    // and includes any amount rolled forward from a previous batch.
    direct: { type: Number, default: 0 },
    matching: { type: Number, default: 0 },
    reversals: { type: Number, default: 0 },
    total: { type: Number, default: 0 },

    // Both charges are 5% of the GROSS total — neither compounds on the other.
    adminCharge: { type: Number, default: 0 },
    secondaryCharge: { type: Number, default: 0 },
    netPayable: { type: Number, default: 0 },

    // ------------------------------------------------------------------
    // Pre-flush carry — the ONLY record of what the closing destroyed.
    // ------------------------------------------------------------------
    // Carry is a running balance whose value depends on the order members were
    // placed in, and that order cannot be reconstructed from the ledger. Once
    // flushed it is gone. Without this snapshot, "what did I lose at closing?"
    // has no answer and a batch generated by mistake cannot be undone.
    carryBefore: {
      left: { type: Number, default: 0 },
      right: { type: Number, default: 0 }
    },

    // What the flush ACTUALLY removed. Usually equal to carryBefore, but lower
    // when a placement made after the cutoff paired off some of the approved
    // carry before the closing ran — the subtraction is clamped at zero rather
    // than driving carry negative.
    //
    // Cancel restores from THIS, not from carryBefore: restoring the snapshot
    // when less was taken would hand the member carry they never had.
    carryFlushed: {
      left: { type: Number, default: 0 },
      right: { type: Number, default: 0 }
    },

    // Rolled forward from a previous batch that netted negative, or that fell
    // under the minimum payable threshold.
    openingAdjustment: { type: Number, default: 0 },
    // Set when this line's own total is carried into the NEXT batch instead of
    // being paid, so the reason is visible on the statement.
    heldReason: { type: String, enum: ['negative', 'below-minimum', null], default: null },

    ledgerRowCount: { type: Number, default: 0 }
  },
  { timestamps: true }
);

// One line per member per batch.
payoutLineSchema.index({ batch: 1, memberCode: 1 }, { unique: true });
// A member's own payout history — the portal view.
payoutLineSchema.index({ member: 1, createdAt: -1 });
// Search within a batch.
payoutLineSchema.index({ batch: 1, netPayable: -1 });

module.exports = mongoose.model('PayoutLine', payoutLineSchema);
